version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - frontend
